version: "3"
services:
    docker-express:
        build:
            context: .
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
        command: npm run start